// ==UserScript==
// @name          DuckDuckGo DeepDark
// @namespace     https://github.com/
// @author        RaitaroH
// @homepage      https://github.com/RaitaroH/DuckDuckGo-DeepDark
// @include       http://duckduckgo.com/*
// @include       https://duckduckgo.com/*
// @include       http://*.duckduckgo.com/*
// @include       https://*.duckduckgo.com/*
// @run-at        document-start
// @version       0.20160108091758
// ==/UserScript==
(function() {var css = [

	".svg .header__logo,.svg.dark-header .header__logo {",
	"	background-image: url(https://i.imgur.com/u6PSvJ3.png) !important;",
	"}",
        ".svg .logo_homepage {",
	"	background-image: url(https://i.imgur.com/9Gj7Fe1.png) !important;",
	"}",
        ".search-filter--region .search-filter__icon, .search-filter--region .dark-header .search-filter__icon, .dark-header .nav-menu__item__icon--region, .dark-bg .search-filter--region .search-filter__icon, .search-filter--region .dark-bg .search-filter__icon, .dark-bg .nav-menu__item__icon--region {",
	"	background-image: url(/assets/icon_region_dark.svg) !important;",
	"}",	
	"a:hover,.result__url__domain,.corner_btn.reset:hover,.zci--timer .corner_btn.add_minute,.result__url:hover,.no-touch .header-wrap .zcm__link.is-active:hover,.no-touch .site-wrapper .zcm__link:hover, .zcm__link:hover, .zcm__link:visited,.logo_homepage__tt,.a:link:hover,.highlight .result__a:hover,a.result__menu:hover{",
	"	color: rgba(0,173,238,.9)  !important;",
	"}",
        ".result__url__domain:hover,.module__title,.result__a:hover{",
	"color: #00adee !important;",
	"text-shadow: 0px 0px 3px rgba(0,173,238,.5) !important;",
	"}",
	".zcm__link.is-active,.zci--timer .play_pause .first_half_fill, .zci--timer .play_pause .rotated_fill{",
	"border-color: #00adee !important;",
	"}",
	".modal__header__title{",
	"border-color: #ccc !important;",
	"}",
	".sitelinks_td:hover,.result:hover,.result.highlight,.logo_homepage__tt {",
	"	background-color: #222 !important;",
	"}",
        ".module__text,.prettyprint .pln,.prettyprint .pun{",
	"color: #ccc !important;",
	"}",
	".zci--timer #add_timer_container,.zci--timer .corner_btn.add_minute{",
	"	background: transparent !important;",
	"}",
	".fe_icon, .fe_icon--alt{",
	"	filter: invert(100%) !important;",
	"}",
	
	"#twitter_status,#ads,.feedback-btn,.nav-menu--slideout .badge-link,.logo_homepage__tt::before,.badge-link{",
	"display : none!important;",
	"}",
	"body,.body--home,.site-wrapper,.modal__box,.sitelinks_td {",
	"	background-color: #111!important;",
	"}",
	".region-switch__label,.tag-home__link,.tag-home__link:hover,.tag-home__link:visited,.tag-home__link:active,.tag-home__nav__close:hover,.results,.msg,.feedback-btn__icon:hover,.feedback-btn__send:hover,.feedback-btn__icon:focus,.feedback-btn__send:focus {",
	"	color: #c2c2c2!important;",
	"}",
	".tag-home__nav__wrap:hover {",
	"	background-color: #4b4b4b!important;",
	"}",
	".result__check {",
	"	color: #111!important;",
	"}",
	".result__check:visited,.feedback-btn,.feedback-btn:hover {",
	"	color: #434343!important;",
	"}",
	".result__a,.result__a:active,.highlight .result__a,.result__a:visited,.tag-home,.page-settings,.frm__label,.no-results__related-search a,.no-results__related-search a:visited,.no-results__related-search a:active,.no-results__related-search a:hover,.modal__box,.modal__header__title,.modal__list__link,.modal__list__link:hover,.modal__list__link:visited,.modal__list__link:focus,.modal__list__link.is-active,.modal__list__link.is-highlighted,.feedback-btn__icon,.feedback-btn__send,.feedback-modal .frm__label {",
	"	color: #fff !important;",
	"}",
	".settings-page-wrapper .set-side a,.settings-page-wrapper .set-side a:hover,.settings-page-wrapper .set-side a:active {",
	"	color: #e6e6e6!important;",
	"	text-decoration: underline!important;",
	"}",
	".btn--top,.result--sep--hr:before,.result--load-btn,.feedback--button.btn--wire {",
	"	color: #c2c2c2!important;",
	"	border-color: #434343!important;",
	"	background-color: #434343!important;",
	"}",
	".btn--top:hover,.feedback--button.btn--wire:hover {",
	"	color: #e6e6e6!important;",
	"	background-color: #434343!important;",
	"}",
	".results--powered {",
	"	color: #c2c2c2!important;",
	"}",
	".set-bookmarklet,.set-reset,.set-head,.set-thumbnail__img,.set-main-footer,.frm__color__swatch {",
	"	border-color: #434343!important;",
	"}",
	".cloudsave,.modal__list__link:hover,.modal__list__link.is-active,.modal__list__link.is-highlighted,.modal--region-filter .modal__list__link.is-highlighted {",
	"	background-color: #434343!important;",
	"}",
	".set-bookmarklet__input,.set-bookmarklet__data,.btn,.btn:visited,.btn:hover,.frm__input {",
	"	background-color    : #4b4b4b!important;",
	"	border-color: #434343!important;",
	"	color: #c2c2c2!important;",
	"}",
	".add-to-browser__directions .btn.btn--primary {",
	"	background-color: #434343!important;",
	"	border-color: transparent!important;",
	"	color: #e6e6e6!important;",
	"}",
	".frm__hr,.btn:active {",
	"	border-color: #434343!important;",
	"}",
	".btn.is-active,.btn.btn--primary,.btn--primary:hover,.is-checked .btn.frm__switch__label {",
	"	color: #111!important;",
	"	border-color: #434343!important;",
	"	background-color: #c2c2c2!important;",
	"}",
	".switch,.region-flag__bg {",
	"	background-color: #4b4b4b!important;",
	"}",
	".region-switch__label-status-on {",
	"	color: #e6e6e6!important;",
	"}",
	".modal--popover.is-showing,.modal--popover--dk.is-showing {",
	"	background: rgba(0,0,0,0.6)!important;",
	"}",
	".modal__box {",
	"	border: 1px solid #292929!important;",
	"}",
	".modal__header {",
	"	background-color: #292929!important;",
	"	border-bottom-color: #292929!important;",
	"}",
	".modal--popout--bottom.has-header .modal__box:before,.modal--popout--bottom-right.has-header .modal__box:before,.modal--popout--bottom-left.has-header .modal__box:before,.modal--popout--bottom.has-header .modal__box:after,.modal--popout--bottom-right.has-header .modal__box:after,.modal--popout--bottom-left.has-header .modal__box:after,.modal--popout .modal__box:before {",
	"	color: #292929!important;",
	"}",
	".modal--popout .modal__box:after {",
	"	color: #111!important;",
	"}",
	".nav-menu,.nav-menu--slideout {",
	"	background-color: #292929!important;",
	"}",
	".nav-menu--slideout {",
	"	border-left-color: #242424!important;",
	"	-webkit-box-shadow: none!important;",
	"	-moz-box-shadow: none!important;",
	"	box-shadow: none!important;",
	"}",
	".nav-menu__icon,.nav-menu__close,.nav-menu__item,.nav-menu__item--secondary,.nav-menu__item > a,.nav-menu__item--secondary > a,.nav-menu__item > a:visited,.nav-menu__item--secondary > a:visited {",
	"	color: #c2c2c2!important;",
	"}",
	".nav-menu__item > a:hover {",
	"	color: #e6e6e6!important;",
	"}",
	".nav-menu__heading,.nav-menu__heading--primary {",
	"	color: #aaaaaa!important;",
	"}",
	".nav-menu__theme.theme-is-selected {",
	"	border-color: #aaaaaa!important;",
	"}",
	".result__snippet,.result__snippet b,.result__snippet a,.result__snippet a:hover,.result__snippet a:active,.result__snippet a:visited {",
	"	color: #c2c2c2 !important;",
	"}",
	".result__url,.result__url:visited,.result__url:active,a.result__menu,a.result__menu:active,a.result__menu:visited,.result--ad .result__url,.result--ad .result__url:hover,.result--ad .result__url:active,.result--ad .result__url:visited,.sponsored__sitelink, .sponsored__sitelink b, .sponsored__sitelink:visited,.sponsored__sitelink:hover {",
	"	color: #c2c2c2!important;",
	"}",
	".msg--result.highlight,.msg--box {",
	"	background: #434343!important;",
	"}",
	".result.result--ad.highlight {",
	"	background: none!important;",
	"}",
	".msg--bang__bang-name {",
	"	color: #c2c2c2!important;",
	"	background-color: #292929!important;",
	"	border-color: #242424!important;",
	"}",
	".msg--bang__bangs-link,.msg--bang__bangs-link:hover,.msg--bang__bangs-link:visited,.msg--bang__bangs-link:active,.msg--spelling :link,.msg--spelling :link:visited,.msg--spelling :link:hover,.msg--spelling :link:active {",
	"	color: #e6e6e6!important;",
	"}",
	"",
	"",
	".header-wrap, .has-active-zci .header-wrap, .has-active-zci .header-wrap .zcm__link:before, .has-active-zci .header-wrap .zcm__link:after, .has-zcm .header-wrap:before, .has-zcm .header-wrap:after, .has-zcm .header-wrap .header:after {",
	"	background-color: #111!important;",
	"}",
	".no-touch .header-wrap .zcm__link.is-active {",
	"	background-color: transparent!important;",
	"}",
	".header-wrap.header-wrap--home {",
	"	background: none!important;",
	"}",
	".has-active-zci .header-wrap {",
	"	border-bottom-color: #2e2e2e!important;",
	"}",
	".header-wrap, .header-wrap--home {",
	"	border-top-color: #242424!important;",
	"}",
	".site-wrapper-border {",
	"	background-color: #242424!important;",
	"}",
	".no-touch .site-wrapper .zcm__link, .zcm__link, .zcm__link:visited {",
	"	color: #cecece!important;",
	"}",
	".zcm__link:hover,.zcm__link:active,.zcm__link.is-active {",
	"	background-color: #111!important;",
	"	color: #e6e6e6!important;",
	"}",
	".no-touch .header-wrap .zcm__link.is-active {",
	"	color: #e6e6e6!important;",
	"}",
	".zcm__sep--h:before {",
	"	border-left-color: #2e2e2e!important;",
	"}",
	".lt-ie9 .header-wrap {",
	"	border-bottom-color: #2e2e2e!important;",
	"}",
	".set-header--menu.has-zcm.is-mobile .header--aside {",
	"	background: -moz-linear-gradient(left, rgba(51, 51, 51,0) 0%, rgba(51, 51, 51,1) 40%, rgba(51, 51, 51,1) 100%)!important;",
	"	background: -webkit-linear-gradient(left, rgba(51, 51, 51,0) 0%, rgba(51, 51, 51,1) 40%, rgba(51, 51, 51,1) 100%)!important;",
	"	background: -o-linear-gradient(left, rgba(51, 51, 51,0) 0%,rgba(51, 51, 51,1) 40%,rgba(51, 51, 51,1) 100%)!important;",
	"	background: -ms-linear-gradient(left, rgba(51, 51, 51,0) 0%, rgba(51, 51, 51,1) 40%, rgba(51, 51, 51,1) 100%)!important;",
	"	background: linear-gradient(to right, rgba(51, 51, 51,0) 0%, rgba(51, 51, 51,1) 40%, rgba(51, 51, 51,1) 100%)!important;",
	"}",
	".is-mobile .zcm-wrap--header:before,.is-mobile .zcm-wrap--header:after {",
	"	background: -moz-linear-gradient(left, rgba(51, 51, 51,0) 0%, rgba(51, 51, 51,1) 50%, rgba(51, 51, 51,0) 100%)!important;",
	"	background: -webkit-gradient(linear, left top, right top, color-stop(0%,rgba(51, 51, 51,0)), color-stop(50%,rgba(51, 51, 51,1)), color-stop(100%,rgba(51, 51, 51,0)))!important;",
	"	background: -webkit-linear-gradient(left, rgba(51, 51, 51,0) 0%,rgba(51, 51, 51,1) 50%,rgba(51, 51, 51,0) 100%)!important;",
	"	background: -o-linear-gradient(left, rgba(51, 51, 51,0) 0%,rgba(51, 51, 51,1) 50%,rgba(51, 51, 51,0) 100%)!important;",
	"	background: -ms-linear-gradient(left, rgba(51, 51, 51,0) 0%,rgba(51, 51, 51,1) 50%,rgba(51, 51, 51,0) 100%)!important;",
	"	background: linear-gradient(to right, rgba(51, 51, 51,0) 0%,rgba(51, 51, 51,1) 50%,rgba(51, 51, 51,0) 100%)!important;",
	"}",
	".btn--icon,.header__button--menu,.no-touch .btn--icon,.no-touch .header__button,.no-touch .header__button--menu {",
	"	color: #b6b6b6!important;",
	"}",
	".header--aside__msg,.header--aside__msg:hover {",
	"	color: #cecece!important;",
	"}",
	".no-touch .btn--icon:hover,.no-touch .header__button:hover,.no-touch .header__button--menu:hover, .no-touch .header__button:focus, .no-touch .header__button--menu:focus {",
	"	color: #242424!important;",
	"	background-color: #cecece!important;",
	"}",
	".search--home,.search--header {",
	"	background-color: #292929!important;",
	"	border-color: #242424!important;",
	"}",
	".search__clear,.search__button,.search--home.has-text .search__clear {",
	"	color: #e6e6e6!important;",
	"}",
	".search__button:hover,.search__button--active,.search:hover .search__button,.search__input:focus ~ .search__button,.search--header.has-text.search--hover .search__button,.search--header.has-text.search--focus .search__button,.search--home.has-text .search__button,.search__button:focus,.search:hover .search__button:focus,.search--header.has-text.search--hover .search__button:hover,.search--header.has-text.search--focus .search__button:hover,.search--home.has-text .search__button:focus,.search--home.has-text .search__button:hover {",
	"	background-color: #1f1f1f!important;",
	"}",
	".search__input--adv {",
	"	color: #e6e6e6!important;",
	"}",
	".search__autocomplete,.acp-wrap__column.acp-wrap__column--left {",
	"	border-color: #2e2e2e!important;",
	"}",
	".acp-wrap,.acp-footer {",
	"	background-color: rgb(36,36,36)!important;",
	"	border-color: #2e2e2e!important;",
	"}",
	".acp, .acp--bang {",
	"	color: #aaaaaa!important;",
	"}",
	".acp strong,.acp--bang .acp--bang__phrase,.acp--highlight.acp--bang .acp--bang__phrase,.acp--highlight.acp--bang .acp--bang__snippet {",
	"	color: #dadada!important;",
	"}",
	".acp--highlight {",
	"	background-color: #545454!important;",
	"}",
	".zci, .zci:before,.tileview .metabar--fixed,.tileview--grid .metabar--fixed,.tileview--grid .metabar--fixed.is-stuck,.mapview.is-expanded .zci {",
	"	background-color: #181818 !important;",
	"	border-bottom-color: #1f1f1f !important;",
	"}",
	".zci-wrap {",
	"	background-color: #292929!important;",
	"}",
	".set-header--fixed .tileview--grid .metabar--fixed,.tileview--grid .metabar--fixed.is-stuck {",
	"	background-color: #292929!important;",
	"	border-top-color: #292929!important;",
	"}",
	".zci.is-active {",
	"	border-bottom-color: #242424!important;",
	"}",
	".zci__body,.zci__detail,.zci__caption,.zci__header,.zci__body h1, .zci__detail h1,.zci__body h2, .zci__detail h2,.zci__body h3, .zci__detail h3,.zci__body h4, .zci__detail h4,.zci__body h5, .zci__detail h5,.zci__body h6, .zci__detail h6,.metabar,.c-detail__title,.c-detail__title__sub,.c-detail__desc,.c-detail__filemeta,.c-detail__more,.c-detail__user,.c-detail__count,.c-detail__date,.c-info,.c-info__title,.c-icon,.c-icon__title,.c-icon__content,.c-score,.metabar__dropdown__selected,.metabar__dropdown__selected:hover,.metabar__dropdown__selected:focus {",
	"	color: #dadada!important;",
	"}",
	".detail--l .detail__media, .detail--products .detail__media, .detail--qa .detail__media, .detail--about .detail__media,.detail--l .detail__media:after, .detail--products .detail__media:after, .detail--qa .detail__media:after, .detail--about .detail__media:after {",
	"	background: none!important;",
	"}",
	"a,a.no-visited,.zci__body a,.zci__detail a,.zcm__link--sub,.zcm__link--sub:visited,.zci__body .chomp--link,.metabar .zci__more-at,.zci__body .zci__more-at,.zci__body .c-detail__rating :link,.zci__more-at,.tile--loc__more,.c-info__link,.c-icon__link,.chomp--link__mr,.chomp--link__ls {",
	"	color: #e6e6e6!important;",
	"}",
	".zci__body a:hover,.detail__body a:hover,.zci__body a:active,.zci__body a:active,.zcm__link--sub.is-here,.zcm__item.is-here .zcm__link--sub,.zci__body .chomp--link:hover,.zci__more-at:hover,.c-info__link:hover,.c-icon__link:hover,.zcm__link--sub:hover,.zcm__link--sub.is-highlighted,.chomp--link:hover .chomp--link__mr,.chomp--link:hover .chomp--link__ls {",
	"	color: #c2c2c2!important;",
	"}",
	".zci pre,.zci code {",
	"	color: #b6b6b6!important;",
	"	background-color: #434343!important;",
	"}",
	".zci pre,.zci code,.c-list__items,.record__cell {",
	"	border-color: #1f1f1f!important;",
	"}",
	".metabar__mode {",
	"	background-color: #434343!important;",
	"}",
	".metabar__mode.is-disabled,.metabar__mode.is-disabled:hover,.metabar__mode.is-disabled:active {",
	"	color: #434343!important;",
	"	background-color: transparent!important;",
	"}",
	".detail {",
	"	background-color: #242424!important;",
	"	border-color: #1f1f1f!important;",
	"}",
	".detail__close {",
	"	color: #4b4b4b!important;",
	"}",
	".detail__close:hover,.detail__close:active {",
	"	color: #545454!important;",
	"}",
	".detail__media--pr {",
	"	border-right-color: #1f1f1f!important;",
	"}",
	".tile--img:after {",
	"	border-bottom-color: #292929!important;",
	"}",
	".sep,.sep--small,.sep--before:before,.sep--after:after {",
	"	border-color: #4b4b4b!important;",
	"}",
	".mapview.is-expanded .metabar,.tileview--grid .metabar--fixed:before  {",
	"	background-color: #292929!important;",
	"}",
	".tile-nav.can-scroll,.tile-nav.can-scroll:after,.tile-nav.can-scroll:hover {",
	"	background-color: #2e2e2e !important;",
	"}",
	".chomp--link__icn,.count__i:after {",
	"	color: #747474!important;",
	"}",
	".tile-nav--sm {",
	"	color: #cecece!important;",
	"	background-color: #4b4b4b!important;",
	"}",
	".tile-nav--sm:hover,.tile-nav--sm:active {",
	"	background-color: #545454!important;",
	"}",
	".c-detail__links__btn,.zci .btn--primary,.zci .btn.btn--primary,.c-detail__links__btn:hover,.zci .btn--primary:hover,.zci__body a.btn--primary:hover {",
	"	color: #cecece!important;",
	"	background-color: #4b4b4b!important;",
	"	border-color: #1f1f1f!important;",
	"}",
	".star,.count__i,.tileview__message,.tileview__message:before,.tile--loc .tile__media__no-img  {",
	"	color: #4b4b4b!important;",
	"}",
	".tile, .tile--s, .tile--info .tile--map {",
	"	border-color: #1f1f1f!important;",
	"}",
	".highlight.tile, .highlight.tile--s, .highlight.tile--info, .highlight.tile--map,.is-selected.tile, .is-selected.tile--s, .is-selected.tile--info, .is-selected.tile--map,.highlight.tile--f .tile--f__main, .highlight.tile--f .tile--f__alt, .is-selected.tile--f .tile--f__alt {",
	"	border-color: #646464!important;",
	"	outline-color: #646464!important;",
	"}",
	".highlight.tile--no-highlight, .highlight.tile--no-highlight:active, .tile--no-highlight.is-selected {",
	"	border-color: #1f1f1f!important;",
	"	outline: none!important;",
	"}",
	".tile--m {",
	"	background-color: #111!important;",
	"	color: #e6e6e6!important;",
	"}",
	".tile--m:hover {",
	"	background-color: #1f1f1f!important;",
	"	color: #c2c2c2!important;",
	"}",
	".tile--m:active,.tile--m.is-loading,.tile--m.is-loading:hover {",
	"	background-color: #111!important;",
	"	color: #111!important;",
	"}",
	".has-tiles--grid .tile--m--images,.has-tiles--grid .tile--m--images:hover,.has-tiles--grid .tile--m--images.is-loading,.is-mobile .has-tiles--grid .tile--m,.is-mobile .has-tiles--grid .tile--m:hover {",
	"	background-color: #111!important;",
	"	border-color: #242424!important;",
	"}",
	".bg-clr--dk,.bg-clr--dk2,.bg-clr--slate,.bg-clr--slate-light  {",
	"	background-color: #dadada!important;",
	"}",
	".bg-clr--lt,.bg-clr--lt2,.bg-clr--lt3,.bg-clr--grey-dark,.bg-clr--grey-light,.bg-clr--grey {",
	"	background-color: #cecece!important;",
	"}",
	".text--primary,.tx-clr--dk,.tx-clr--dk2,.tx-clr--slate,.tx-clr--slate-light {",
	"	color: #dadada!important;",
	"}",
	".zci__subheader,.zci__header__sub,.c-info__sub,.c-info__title__sub,.c-icon__sub,.c-score__head,.c-score__foot,.text--secondary,.tx-clr--grey-dark,.tx-clr--grey-light,.tx-clr--grey,.tx-clr--lt,.tx-clr--lt2,.tx-clr--lt3 {",
	"	color: #cecece!important;",
	"}",
	".tile, .tile__title, .tile h4, .tile--m--mob, .at-topic .tile__title, .at-topic .tile.active-topic .tile__title, .at-topic .tile.highlight .tile__title, .is-mobile .c-info__link, .is-mobile .c-info__link:hover, .tile--loc, .tile .tile__price b {",
	"	color: #dadada!important;",
	"}",
	".tile, .tile--s, .bg-tile, .tile--m--mob, .tile__media--pr, .at-topic .tile.active-topic, .at-topic .tile.highlight, .tile__foot--news, .tile--f__main, .tile--f__alt, .tile__num:before, .is-mobile .c-info__link, .is-mobile .c-info__link:hover, .tile__media .tile__media__img {",
	"	background-color: #222 !important;",
	"}",
	".tile__expand, .tile__expand:hover,.bg-clr--platinum-darker,.bg-clr--platinum-dark,.bg-clr--platinum-light,.bg-clr--platinum,.bg-clr--silver-dark,.bg-clr--silver-light,.bg-clr--silver {",
	"	background: #4b4b4b!important;",
	"}",
	".at-topic .tile,.tile--loc .tile__media__no-img {",
	"	background: #292929!important;",
	"}",
	".tile__sub, .tile__sub--2, .tile__title__sub, .tile__foot, .tile__footer, .tile__link, .tile--audio .tile__footer, .tile__count, .tile--b--i .tile__source, .tile__neighborhood, .tile__more-at, .tile__title a:visited,.tx-clr--platinum-darker, .tx-clr--platinum-dark, .tx-clr--platinum-light, .tx-clr--platinum,.tx-clr--silver-dark, .tx-clr--silver-light, .tx-clr--silver {",
	"	color: #c2c2c2!important;",
	"}",
	".tile--b--i .tile__description, .tile__content, .tile__content--qa, .tile__content--news, .tile__tx, .tile__expand, .tile__expand:hover, .tile__num, .tile__phone, .info__label, .info__value, .tile__foot, .tile__foot--news, .attribution--link__icon {",
	"	color: #cecece!important;",
	"}",
	".tile--info .info, .tile__expand, .tile__expand:hover, .attribution__hr, .c-score__line, .c-score__foot, .has-score .c-score__line__name, .is-mobile .no-score .c-score__line--home, .c-score__line--vs1:before, .c-score__line--vs1:after {",
	"	border-color: #292929!important;",
	"}",
	".tile--f__main, .tile--f__alt, .csstransforms3d .tile--f__main, .csstransforms3d .tile--f__alt, .is-mobile .c-info__link {",
	"	border-color: #1f1f1f!important;",
	"}",
	".tile .tile__price {",
	"	color: #242424!important;",
	"}"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node); 
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
